### ISSUE TITLE
[bug]: Invalid DOM Properties Warnings

### ISSUE THREAD

**Issue by hanzili** [keploy/keploy#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I encountered several warnings related to invalid DOM properties during the compilation of pages. Specifically, the warnings are about stop-color, fill-rule, and stroke-width properties in the JSX code, suggesting that they should be written in camelCase (stopColor, fillRule, strokeWidth) to be valid in React.

```
Warning: Invalid DOM property `stop-color`. Did you mean `stopColor`?
    at stop
    at linearGradient
    at defs
    at svg
    at a
    at LinkComponent (webpack-internal:///(ssr)/./node_modules/next/dist/client/link.js:105:19)
    at Logo
    at div
    at div
    at div
    at header
    at Header (webpack-internal:///(ssr)/./components/ui/header.tsx:21:74)
    at Lazy
    at div
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:72:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:80:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)    
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:327:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:145:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:77:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:103:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:382:13)
    at Lazy
    at Lazy
    at ServerComponentWrapper (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\create-server-components-renderer.js:78:31)
    at ServerComponentWrapper (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\create-server-components-renderer.js:78:31)
    at InsertedHTML (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\app-render.js:893:33)
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
    at g
    at svg
    at a
    at LinkComponent (webpack-internal:///(ssr)/./node_modules/next/dist/client/link.js:105:19)
    at Logo
    at div
    at div
    at div
    at header
    at Header (webpack-internal:///(ssr)/./components/ui/header.tsx:21:74)
    at Lazy
    at div
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:72:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:80:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)    
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:327:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:145:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:77:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:103:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:382:13)
    at Lazy
    at Lazy
    at ServerComponentWrapper (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\create-server-components-renderer.js:78:31)
    at ServerComponentWrapper (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\create-server-components-renderer.js:78:31)
    at InsertedHTML (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\app-render.js:893:33)
Warning: Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?
    at g
    at g
    at g
    at svg
    at a
    at LinkComponent (webpack-internal:///(ssr)/./node_modules/next/dist/client/link.js:105:19)
    at LinkComponent (webpack-internal:///(ssr)/./node_modules/next/dist/client/link.js:105:19)
    at Logo
    at div
    at div
    at div
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:145:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:77:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:103:11) 
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:382:13)
    at Lazy
    at Lazy
    at ServerComponentWrapper (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\create-server-components-renderer.js:78:31)
    at ServerComponentWrapper (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\create-server-components-renderer.js:78:31)
    at InsertedHTML (C:\Users\hanzi\Desktop\keploy-website\node_modules\next\dist\server\app-render\app-render.js:893:33)
    ```

### Steps to reproduce

Observe the terminal output for warnings as the development server compiles the home page.

### Environment

None

### Version

Local

### Repository

website

**Comment by its-kunal** [comment]
I'll be working on this issue, and raising a PR soon.
