### ISSUE TITLE
[bug]: Flakiness in Go Test due to race conditions

### ISSUE THREAD

**Issue by aerowisca** [keploy/keploy#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I came across this race condition while running `go test`. Looks like we are accessing a map without a mutex

```fatal error: concurrent map writes

goroutine 469 [running]:
runtime.throw({0xfdaf23?, 0xf25720?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0002b2f88 sp=0xc0002b2f58 pc=0x437db1
runtime.mapassign_faststr(0xe9a840, 0xc0034ed3e0, {0xc0034e6ed8, 0x8})
	/usr/local/go/src/runtime/map_faststr.go:295 +0x38b fp=0xc0002b2ff0 sp=0xc0002b2f88 pc=0x41520b
go.keploy.io/server/pkg/service/testCase.(*TestCase).isDup(0xc0003566e0, {0x203e710, 0xc003794e40}, 0xc0002b3748)
	/home/aerowisca/keploy/pkg/service/testCase/testCase.go:502 +0xa6c fp=0xc0002b3280 sp=0xc0002b2ff0 pc=0xd5c28c
go.keploy.io/server/pkg/service/testCase.(*TestCase).putTC(_, {_, _}, {_, _}, {{0xc003a1ec90, 0x24}, 0x641af62b, 0x641af62b, 0x63cfa919, ...})
	/home/aerowisca/keploy/pkg/service/testCase/testCase.go:175 +0xac fp=0xc0002b3748 sp=0xc0002b3280 pc=0xd56c8c
go.keploy.io/server/pkg/service/testCase.(*TestCase).insertToDB(0xc0003566e0, {0x203e710, 0xc003794e40}, {0xfd4e34, 0xf}, {0xc0002b44f8?, 0x1, 0x0?})
	/home/aerowisca/keploy/pkg/service/testCase/testCase.go:202 +0x225 fp=0xc0002b3c98 sp=0xc0002b3748 pc=0xd578e5
go.keploy.io/server/pkg/service/testCase.(*TestCase).Insert(0xc0003566e0, {0x203e710?, 0xc003794e40}, {0xc003c6ef00?, 0x1, 0xe84220?}, {0xc0000b2300, 0x53}, {0xc0000b2360, 0x53}, ...)
	/home/aerowisca/keploy/pkg/service/testCase/testCase.go:372 +0x8c9 fp=0xc0002b4df0 sp=0xc0002b3c98 pc=0xd58f29
go.keploy.io/server/http/regression.(*regression).PostTC(0xc000121080, {0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/keploy/http/regression/regression.go:207 +0x805 fp=0xc0002b5088 sp=0xc0002b4df0 pc=0xd64ac5
go.keploy.io/server/http/regression.(*regression).PostTC-fm({0x203c9e0?, 0xc003794e10?}, 0xc003515f58?)
	<autogenerated>:1 +0x3c fp=0xc0002b50b8 sp=0xc0002b5088 pc=0xd668dc
net/http.HandlerFunc.ServeHTTP(0xe99ca0?, {0x203c9e0?, 0xc003794e10?}, 0x20329a4?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b50e0 sp=0xc0002b50b8 pc=0x75d60f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00007cc60, {0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9 fp=0xc0002b5130 sp=0xc0002b50e0 pc=0x80f0b9
github.com/go-chi/chi.(*Mux).routeHTTP-fm({0x203c9e0?, 0xc003794e10?}, 0xc001b0b1b0?)
	<autogenerated>:1 +0x3c fp=0xc0002b5160 sp=0xc0002b5130 pc=0x8133fc
net/http.HandlerFunc.ServeHTTP(0x0?, {0x203c9e0?, 0xc003794e10?}, 0x26801b0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b5188 sp=0xc0002b5160 pc=0x75d60f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00007cc60, {0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70 +0x48e fp=0xc0002b51f8 sp=0xc0002b5188 pc=0x80cf0e
github.com/go-chi/chi.(*Mux).Mount.func1({0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311 +0x19c fp=0xc0002b5248 sp=0xc0002b51f8 pc=0x80e8bc
net/http.HandlerFunc.ServeHTTP(0xe99ca0?, {0x203c9e0?, 0xc003794e10?}, 0xc0034e6d30?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b5270 sp=0xc0002b5248 pc=0x75d60f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00007cc00, {0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9 fp=0xc0002b52c0 sp=0xc0002b5270 pc=0x80f0b9
github.com/go-chi/chi.(*Mux).routeHTTP-fm({0x203c9e0?, 0xc003794e10?}, 0xc0034e6d30?)
	<autogenerated>:1 +0x3c fp=0xc0002b52f0 sp=0xc0002b52c0 pc=0x8133fc
net/http.HandlerFunc.ServeHTTP(0x0?, {0x203c9e0?, 0xc003794e10?}, 0x4530b0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b5318 sp=0xc0002b52f0 pc=0x75d60f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00007cc00, {0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70 +0x48e fp=0xc0002b5388 sp=0xc0002b5318 pc=0x80cf0e
github.com/go-chi/chi.(*Mux).Mount.func1({0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311 +0x19c fp=0xc0002b53d8 sp=0xc0002b5388 pc=0x80e8bc
net/http.HandlerFunc.ServeHTTP(0xe99ca0?, {0x203c9e0?, 0xc003794e10?}, 0xc001b4e378?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b5400 sp=0xc0002b53d8 pc=0x75d60f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00007cba0, {0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9 fp=0xc0002b5450 sp=0xc0002b5400 pc=0x80f0b9
github.com/go-chi/chi.(*Mux).routeHTTP-fm({0x203c9e0?, 0xc003794e10?}, 0xc001b4e378?)
	<autogenerated>:1 +0x3c fp=0xc0002b5480 sp=0xc0002b5450 pc=0x8133fc
net/http.HandlerFunc.ServeHTTP(0x0?, {0x203c9e0?, 0xc003794e10?}, 0x4530b0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b54a8 sp=0xc0002b5480 pc=0x75d60f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00007cba0, {0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:70 +0x48e fp=0xc0002b5518 sp=0xc0002b54a8 pc=0x80cf0e
github.com/go-chi/chi.(*Mux).Mount.func1({0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:311 +0x19c fp=0xc0002b5568 sp=0xc0002b5518 pc=0x80e8bc
net/http.HandlerFunc.ServeHTTP(0xe99ca0?, {0x203c9e0?, 0xc003794e10?}, 0xc003a1ec35?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b5590 sp=0xc0002b5568 pc=0x75d60f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00007c300, {0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:436 +0x1f9 fp=0xc0002b55e0 sp=0xc0002b5590 pc=0x80f0b9
github.com/go-chi/chi.(*Mux).routeHTTP-fm({0x203c9e0?, 0xc003794e10?}, 0xc003c7ae48?)
	<autogenerated>:1 +0x3c fp=0xc0002b5610 sp=0xc0002b55e0 pc=0x8133fc
net/http.HandlerFunc.ServeHTTP(0xc0005dc640?, {0x203c9e0?, 0xc003794e10?}, 0xc00031ac00?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b5638 sp=0xc0002b5610 pc=0x75d60f
github.com/go-chi/cors.(*Cors).Handler.func1({0x203c9e0, 0xc003794e10}, 0xc00031ac00)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/cors@v1.2.0/cors.go:228 +0x1bd fp=0xc0002b5690 sp=0xc0002b5638 pc=0x81427d
net/http.HandlerFunc.ServeHTTP(0xf33f20?, {0x203c9e0?, 0xc003794e10?}, 0xe?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b56b8 sp=0xc0002b5690 pc=0x75d60f
github.com/keploy/go-sdk/integrations/kchi.(*chiV5).Next(0x203dd00?)
	/home/aerowisca/go/pkg/mod/github.com/keploy/go-sdk@v0.7.9/integrations/kchi/chi-v5.go:64 +0x30 fp=0xc0002b56e8 sp=0xc0002b56b8 pc=0xd96cd0
github.com/keploy/go-sdk/keploy.Middleware(0xc0001064e0, {0x20411a8, 0xc003794db0})
	/home/aerowisca/go/pkg/mod/github.com/keploy/go-sdk@v0.7.9/keploy/router.go:45 +0x1cd fp=0xc0002b59b8 sp=0xc0002b56e8 pc=0xd91fed
github.com/keploy/go-sdk/integrations/kchi.ChiMiddlewareV5.func1.1({0x203dd00?, 0xc00027cc40}, 0xc00031ab00)
	/home/aerowisca/go/pkg/mod/github.com/keploy/go-sdk@v0.7.9/integrations/kchi/chi-v5.go:13 +0xe8 fp=0xc0002b5a00 sp=0xc0002b59b8 pc=0xd96b08
net/http.HandlerFunc.ServeHTTP(0x203e668?, {0x203dd00?, 0xc00027cc40?}, 0x26801b0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc0002b5a28 sp=0xc0002b5a00 pc=0x75d60f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00007c300, {0x203dd00, 0xc00027cc40}, 0xc00031a800)
	/home/aerowisca/go/pkg/mod/github.com/go-chi/chi@v1.5.4/mux.go:87 +0x442 fp=0xc0002b5a98 sp=0xc0002b5a28 pc=0x80cec2
net/http.serverHandler.ServeHTTP({0x203b540?}, {0x203dd00, 0xc00027cc40}, 0xc00031a800)
	/usr/local/go/src/net/http/server.go:2916 +0x43b fp=0xc0002b5b58 sp=0xc0002b5a98 pc=0x7610bb
net/http.(*conn).serve(0xc000525c20, {0x203e710, 0xc00015ec30})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7 fp=0xc0002b5fb8 sp=0xc0002b5b58 pc=0x75c0b7
net/http.(*Server).Serve.func3()
	/usr/local/go/src/net/http/server.go:3071 +0x2e fp=0xc0002b5fe0 sp=0xc0002b5fb8 pc=0x761a0e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0002b5fe8 sp=0xc0002b5fe0 pc=0x46b181
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db```

### Steps to reproduce

Run the go test command a couple of times on the latest codebase.

### Environment

None

### Version

Local

**Comment by charankamarapu** [comment]
Issue is irrelevant as keploy v1 is no more supported.
