### ISSUE TITLE
[bug]: invalid memory address or nil pointer dereference from MockRespFromYaml when using SQL and HTTP mocks

### ISSUE THREAD

**Issue by youssefsiam38** [keploy/keploy#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to use Keploy to generate SQL and HTTP mocks in the context of the same request.

As you see in the screenshot j.Spec.Req is nil in the SQL mock. I can guess from the function name that it should not be called for this mock

![image](https://github.com/keploy/keploy/assets/54387513/910b1e3a-810d-441d-8ecb-444115746c49)

Here is how I added the interceptor (Gin is the framework)

```
client := goshopify.NewClient(sh.app, shopDomain, accessToken, func(c *goshopify.Client) {
		interceptor := khttpclient.NewInterceptor(http.DefaultTransport)
		interceptor.SetContext(ctx.Request.Context())
		c.Client.Transport = interceptor
	})
```

error message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfa6e9b]

goroutine 123 [running]:
github.com/keploy/go-sdk/integrations/khttpclient.MockRespFromYaml(0xc00052ec00, 0xc0001e60e0, 0xc001c0ef00, {0xc0001cb200, 0x0, 0x200}, 0xc0011c5e00)
	/home/youssef/go/pkg/mod/github.com/keploy/go-sdk@v0.8.6/integrations/khttpclient/utils.go:50 +0x39b
github.com/keploy/go-sdk/integrations/khttpclient.Interceptor.RoundTrip({{0x16b6880, 0xc000a96500}, 0xc0001e60e0, 0xc00052ec00}, 0xc001c0ef00)
	/home/youssef/go/pkg/mod/github.com/keploy/go-sdk@v0.8.6/integrations/khttpclient/httpClient.go:162 +0xd59
net/http.send(0xc001c0ed00, {0x16b4c00, 0xc00150a3c0}, {0xc11e503dcbc5edcc, 0xb26fc1af9, 0x1d2db20})
	/usr/local/go/src/net/http/client.go:252 +0x4c4
net/http.(*Client).send(0xc0011c5b90, 0xc001c0ed00, {0xc11e503dcbc5edcc, 0xb26fc1af9, 0x1d2db20})
	/usr/local/go/src/net/http/client.go:176 +0x165
net/http.(*Client).do(0xc0011c5b90, 0xc001c0ed00)
	/usr/local/go/src/net/http/client.go:716 +0x116c
net/http.(*Client).Do(0xc0011c5b90, 0xc001c0ed00)
	/usr/local/go/src/net/http/client.go:582 +0x4f
github.com/bold-commerce/go-shopify/v3.(*Client).doGetHeaders(0xc000387880, 0xc001c0ed00, {0x13fe520, 0xc0006c4330})
	/home/youssef/go/pkg/mod/github.com/bold-commerce/go-shopify/v3@v3.13.0/goshopify.go:331 +0x15e
github.com/bold-commerce/go-shopify/v3.(*Client).createAndDoGetHeaders(0xc000387880, {0x15cf37c, 0x3}, {0xc00061c760, 0x19}, {0x0, 0x0}, {0x0, 0x0}, {0x13fe520, ...})
	/home/youssef/go/pkg/mod/github.com/bold-commerce/go-shopify/v3@v3.13.0/goshopify.go:616 +0x2dc
github.com/bold-commerce/go-shopify/v3.(*Client).CreateAndDo(0xc000387880, {0x15cf37c, 0x3}, {0xc0013c4288, 0x13}, {0x0, 0x0}, {0x0, 0x0}, {0x13fe520, ...})
	/home/youssef/go/pkg/mod/github.com/bold-commerce/go-shopify/v3@v3.13.0/goshopify.go:596 +0xec
github.com/bold-commerce/go-shopify/v3.(*Client).Get(0xc000387880, {0xc0013c4288, 0x13}, {0x13fe520, 0xc0006c4330}, {0x0, 0x0})
```

Please let me know if you need more info

### Steps to reproduce

1. Set record mode
1. Send a request to a handler that sends SQL queries and many HTTP requests, that needs to be mocked

### Environment

None

### Version

Local

### Repository

go-sdk

**Comment by deepto98** [comment]
I'm trying to reproduce this as well, I'd also need a code sample which causes the error.

**Comment by youssefsiam38** [comment]
@slayerjain @Sarthak160 @deepto98 Thanks for your prompt responses

- #### The Sample code... 
```go
package main

import (
	"database/sql"
	"fmt"
	ioutil "io"
	"log"
	stdHttp "net/http"
	"os"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/keploy/go-sdk/integrations/kgin/v1"
	"github.com/keploy/go-sdk/integrations/khttpclient"
	"github.com/keploy/go-sdk/integrations/ksql/v1"
	"github.com/keploy/go-sdk/keploy"
	"github.com/lib/pq"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func setupRouter(r *gin.Engine, db *gorm.DB, interceptor *khttpclient.Interceptor) *gin.Engine {
	// Test http call
	r.POST("/test_http_and_sql", func(c *gin.Context) {

		interceptor.SetContext(c.Request.Context())

		client := stdHttp.Client{
			Transport: interceptor,
		}

		req, err := stdHttp.NewRequest("GET", "https://catfact.ninja/fact", nil)
		if err != nil {
			c.JSON(500, gin.H{
				"message": err.Error(),
			})
			return
		}

		resp, err := client.Do(req)
		if err != nil {
			c.JSON(500, gin.H{
				"message": err.Error(),
			})
			return
		}
		defer resp.Body.Close()

		body, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			c.JSON(500, gin.H{
				"message": err.Error(),
			})
			return
		}

		txn := db.WithContext(c.Request.Context()).Exec("SELECT 1")
		if txn.Error != nil {
			c.JSON(500, gin.H{
				"message": txn.Error.Error(),
			})
			return
		}

		c.Data(200, "application/json", body)
	})

	return r
}

func main() {

	dbHost := "localhost"
	dbPort := "5432"
	dbUser := "postgres"
	dbPassword := "postgres"
	dbName := "postgres"

	dsn := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable", dbHost, dbPort, dbUser, dbPassword, dbName)

	newLogger := logger.New(
		log.New(os.Stdout, "\r\n", log.LstdFlags), // io writer
		logger.Config{
			SlowThreshold:             time.Second, // Slow SQL threshold
			LogLevel:                  logger.Warn, // Log level
			IgnoreRecordNotFoundError: true,        // Ignore ErrRecordNotFound error for logger
			ParameterizedQueries:      false,       // Don't include params in the SQL log
			Colorful:                  true,
		},
	)

	driver := ksql.Driver{Driver: &pq.Driver{}}

	sql.Register("keploy", &driver)

	db, err := gorm.Open(postgres.Dialector{
		Config: &postgres.Config{
			DriverName: "keploy",
			DSN:        dsn,
		},
	}, &gorm.Config{
		Logger:               newLogger,
		DisableAutomaticPing: true,
	})
	if err != nil {
		log.Fatal("Error: ", err)
	}

	k := keploy.New(keploy.Config{
		App: keploy.AppConfig{
			Name: "test-bug",
			Port: "8080",
			Host: "localhost",
		},
		Server: keploy.ServerConfig{
			URL: "http://localhost:6789/api",
		},
	})

	r := gin.Default()

	kgin.GinV1(k, r)

	interceptor := khttpclient.NewInterceptor(stdHttp.DefaultTransport)

	r = setupRouter(r, db, interceptor)
	err = r.Run(":8080")
	if err != nil {
		log.Fatal("Error: ", err)
	}
}
```
> **Warning**
> Don't forget to change the 	dbHost, dbPort, dbUser, dbPassword and dbName variables

- #### No, I don't think there are any async HTTP calls

- #### go-sdk version: 

```go
	github.com/keploy/go-sdk v0.8.9
```

- #### I am using Keploy for generating mocks and also for e2e testing

Please let me know if you need any more info...

**Comment by deepto98** [comment]
@youssefsiam38 Thanks, I was able to reproduce the issue, looking into it now

**Comment by Sarthak160** [comment]
Cool ! basically in KEPLOY_MODE=test we simulate the same req to client that we have captured and stored in a YAML . So when we Read the responses of mock data captured earlier we are using a function `MockRespfromYaml` which also does the approximate match which determines the priority to which ingress request this mock should be part of this we usually do by comparing the different req response parameters . But in case , we are having mocks of 2 different kind and other one is not `HTTP` , let’s say `SQL` . It returns nil pointer dereference when we try to `reqUrl, er := url.Parse(j.Spec.Req.URL)`

So just by adding a check if it’s not http before accessing the req url as that field would not be available in the SQL spec of a mock

**Comment by deepto98** [comment]
Thanks @Sarthak160, I'm working on the fix.

**Comment by deepto98** [comment]
I raised a PR for this in the Go SDK (https://github.com/keploy/go-sdk/pull/191), thanks for the help @Sarthak160.
